JINC= -I /home/h6/julia_v3/src  -I /home/h6/julia_v3/ui -I /home/h6/julia_v3/src/support \
	-I /home/h6/julia_v3/usr/include -L /home/h6/julia_v3/usr/lib -ljulia_v3

repl: repl.c 
	gcc -c repl.c $(JINC)
